"""empty message

Revision ID: 244e84b43818
Revises: a7158f5142fa
Create Date: 2024-01-24 22:28:22.969856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244e84b43818'
down_revision = 'a7158f5142fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('patients_phone_key', type_='unique')

    with op.batch_alter_table('pros', schema=None) as batch_op:
        batch_op.drop_constraint('pros_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pros', schema=None) as batch_op:
        batch_op.create_unique_constraint('pros_phone_key', ['phone'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_unique_constraint('patients_phone_key', ['phone'])

    # ### end Alembic commands ###
