"""empty message

Revision ID: a7158f5142fa
Revises: fbbdb6debf17
Create Date: 2024-01-22 18:37:23.752291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7158f5142fa'
down_revision = 'fbbdb6debf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])

    with op.batch_alter_table('pros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_status', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pros', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('config_status')

    with op.batch_alter_table('hours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
